### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by nueverest** [DanielOaks/http_status#3]
I've created a unit_test on my fork.

**Comment by DanielOaks** [comment]
Awesome! Just as a note, if you could develop these changes in a branch so it's easier to integrate them with the main repo, it'd be great!

**Comment by DanielOaks** [comment]
If you could throw the license over to BSD 2-clause, something similar to this below:

```
#!/usr/bin/env python
# written by Daniel Oaks <daniel@danieloaks.net>, Chad Nelson
# licensed under the BSD 2-clause license
__author__ = 'Daniel Oaks <daniel@danieloaks.net>, Chad Nelson'
```

I'd be able to integrate the latest changes. I also can't use formencode at this time, due to it not supporting Python3, but it shouldn't be too difficult to change that code over to use something 'homebrew', similar to the `validate_http_code` the main code uses right now.

If you have any comments about that sorta change/those sorta changes, feel free to post them here!
